name: shopify_app
description: A new Flutter project.


publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'


dependencies:
  flutter:
    sdk: flutter
  #cupertino style
  cupertino_icons: ^1.0.2
  #animation
  animated_text_kit: ^4.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter


  # flutter_lints: ^2.0.0


flutter:


  uses-material-design: true


  assets:
    - images/accessories/
    - images/bags/
    - images/beauty/
    - images/electronics/
    - images/homegarden/
    - images/kids/
    - images/men/
    - images/shoes/
    - images/women/
    - images/inapp/

  fonts:
    - family: Acme
      fonts:
        - asset: assets/fonts/Acme-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  

